### ISSUE TITLE
Since 3.4.1 problem connecting

### ISSUE THREAD

**Issue by vincent-iQontrol** [shamblett/coap#63]
I'm connecting with a server on a local network for example: 10.0.1.112

Since the latest update 3.4.1 I get the following error.

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: SocketException: Send failed (OS Error: Operation not permitted, errno = 1), address = 0:0:0:0:0:0:0:0, port = 0

#0      _NativeSocket.send (dart:io-patch/socket_patch.dart:1205:34)
#1      _RawDatagramSocket.send (dart:io-patch/socket_patch.dart:2438:15)
#2      CoapNetworkUDP.send (package:coap/src/channel/coap_network_udp.dart:52:18)

**Comment by vincent-iQontrol** [comment]
A work around is to force the client:

_client!.addressType = InternetAddressType.IPv4;

**Comment by JKRhb** [comment]
Oh, sorry, this is caused by #62 which probably should be reverted then.

**Comment by JKRhb** [comment]
I opened #64 in order to resolve this. Sorry for the problems this change has caused :/

**Comment by shamblett** [comment]
Issue should be resolved, please re test, package re published at version 3.4.2
